apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-server-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-server-app
  template:
    metadata:
      labels:
        app: contact-server-app
    spec:
      containers:
        - image: nexus-service.nexus.svc.cluster.local:8085/zzahid99/contact-server-kubernetes-app:latest
          name: container1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: server-side-configs
            - secretRef:
                name: server-side-secrets
      imagePullSecrets:
          - name: regcred