apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-server-app
  template:
    metadata:
      labels:
        app: contact-server-app
    spec:
      containers:
      - image: contact-server-kubernetes-app:latest
        name: container1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets